# @package _global_

defaults:
  - /model: segformer_b0
  - _self_

seed: 42
device: cuda

epochs: 50
batch_size: 8
num_workers: null
freeze: "encoder"  # [none, encoder, classifier]

huggingface:
  repo_id: "Mirali33/mb-s5mars"
  token: "HF_TOKEN_PLACEHOLDER"
  use_auth_token: true
  cache_dir: null

splits:
  train: "train"
  val: "val"
  test: "test"

transforms:
  enabled: true
  resize:
    enabled: true
    height: 512
    width: 512
  normalize:
    enabled: true
    mean: ${model.image_mean}
    std: ${model.image_std}

dataloader:
  batch_size: ${batch_size}
  shuffle: true
  num_workers: ${num_workers}
  pin_memory: true
  drop_last: false

optimizer:
  name: adamw
  lr: 0.00006
  weight_decay: 0.01

scheduler:
  name: cosine
  warmup_epochs: 3

criterion:
  name: "cross_entropy"   # [cross_entropy, generalized_dice, combined]
  alpha: 0.5              # combined loss: alpha * CE + (1 - alpha) * GDL
  weight_type: "square"   # [uniform, simple, square]
  smooth: 1e-5

checkpoint:
  output_dir: ${paths.output_dir}
  save_best: true
  monitor: val_miou
  mode: max

eval:
  metrics:
    - pixel_accuracy
    - mean_iou
    - per_class_iou

dataset:
  image_column: image
  mask_column: mask
  width_column: width
  height_column: height
  class_labels_column: class_labels
  image_mode: RGB
  ignore_index: ${model.ignore_index}
  num_classes: ${model.num_classes}
  class_names:
    0: "Background"
    1: "Bedrock"
    2: "Hole"
    3: "Ridge"
    4: "Rock"
    5: "Rover"
    6: "Sand / Soil"
    7: "Sky"
    8: "Track"

paths:
  output_dir: outputs/${model.name}_s5mars

logging:
  level: INFO
  log_to_file: true
  filename: train.log
